export const galleryItems = [
  {
    icon: 'https://i.pinimg.com/564x/ff/12/f9/ff12f9c62031574824c10d1f3d6b745f.jpg',
    mainCharacter: 'Denji',
    alt: 'On the picture, there is a woman with long pink hair. She is wearing a suit.',
    title: 'Chainsaw Man',
    seasons: 1,
    favorite: false,
    rating: 4,
    tags: ['horror', 'fantasy', 'action', 'supernatural', 'mystery'],
  },
  {
    icon: 'https://i.pinimg.com/564x/df/72/5f/df725fa4356dbc405a83c8f9c096133b.jpg',
    mainCharacter: 'Isagi',
    alt: 'On the picture, there is a young, happy gitl with long black hair and red, hot eyes.',
    title: 'bluelock',
    seasons: 4,
    favorite: false,
    rating: 3.5,
    tags: ['school', 'ecchi', 'psychological', 'hazard'],
  },
  {
    icon: 'https://i.pinimg.com/564x/57/64/ba/5764baca072ceaa5eb62160d927cd898.jpg',
    mainCharacter: 'Jabami Yumeko',
    alt: 'On the picture, there is a young, happy gitl with long black hair and red, hot eyes.',
    title: 'Attack on Titan',
    seasons: 4,
    favorite: false,
    rating: 3.5,
    tags: ['school', 'ecchi', 'psychological', 'hazard'],
  },
  {
    icon: 'https://i.pinimg.com/564x/95/5b/3d/955b3d4589a0882475c9bcfd598dd381.jpg',
    mainCharacter: 'Jabami Yumeko',
    alt: 'On the picture, there is a young, happy gitl with long black hair and red, hot eyes.',
    title: 'Attack on Titan',
    seasons: 4,
    favorite: false,
    rating: 3.5,
    tags: ['school', 'ecchi', 'psychological', 'hazard'],
  },
];
